### ISSUE TITLE
Compilation instructions say backface culling defaults to off

### ISSUE THREAD

**Issue by 0joshuaolson1** [embree/embree.github.com#2]
Is this a website error, a design mistake, or a debugging necessity?

**Comment by svenwoop** [comment]
This is on purpose as the feature costs performance. If you need the feature just recompile Embree.

**Comment by 0joshuaolson1** [comment]
I'm trying to understand this. In OpenGL applications culling speeds things up because all geometry is sorted before it's rendered. Is no culling faster because finding the first ray intersection doesn't get slower with an increase in the size of the compiled data structure to search?

**Comment by svenwoop** [comment]
Sorry, I had our ray masking feature in mind. That one costs some performance when enabled. The backface culling should perform the same. The feature is disabled by default as most customers need the front and back face hits of geometry.

**Comment by 0joshuaolson1** [comment]
Thank you for your patience.
